apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.app.name }}-configmap
data:
    DB_HOST: "{{ .Values.config.db.host | b64enc }}"
    DB_NAME: "{{ .Values.config.db.name  | b64enc }}"
    DB_PORT: "{{ .Values.config.db.port | toString | b64enc }}"
    SERVER_PORT: "{{ .Values.config.server.port }}"
