apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.app.name }}-secrets
type: Opaque
data:
    DB_USERNAME: "{{ .Values.secrets.db.username | b64enc }}"
    DB_PASSWORD: "{{ .Values.secrets.db.password | b64enc }}"
